name: Build FE + BE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ApiGateway, Authentication_Service, Url_Crud_Service, Url_Shorten_Service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build ${{ matrix.service }}
        run: |
          cd server/${{ matrix.service }}
          dotnet restore
          dotnet build --configuration Release

  build_client:
    runs-on: ubuntu-latest
    needs: build_server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

  docker_push:
    runs-on: ubuntu-latest
    needs: [build_server, build_client]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------- Login Docker Hub ----------
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ---------- Build & Push Backend ----------
      - name: Build & Push ApiGateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/apigateway:${{ github.run_number }} -f ./server/ApiGateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/apigateway:${{ github.run_number }}

      - name: Build & Push Authentication_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/authservice:${{ github.run_number }} -f ./server/Authentication_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/authservice:${{ github.run_number }}

      - name: Build & Push Url_Crud_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/urlcrud:${{ github.run_number }} -f ./server/Url_Crud_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/urlcrud:${{ github.run_number }}

      - name: Build & Push Url_Shorten_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/urlshorten:${{ github.run_number }} -f ./server/Url_Shorten_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/urlshorten:${{ github.run_number }}

      # ---------- Build & Push Client ----------
      - name: Build & Push Client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }} -f ./client/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }}


      # ---------- Trigger Render Deploy ----------

      - name: Trigger All Server Services Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_APIGATEWAY_HOOK }}
          curl -X POST ${{ secrets.RENDER_AUTH_HOOK }}
          curl -X POST ${{ secrets.RENDER_URLCRUD_HOOK }}
          curl -X POST ${{ secrets.RENDER_URLSHORTEN_HOOK }}

      - name: Trigger Client Deploy
        run: curl -X POST ${{ secrets.RENDER_CLIENT_HOOK }}
