name: Build FE + BE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ApiGateway, Authentication_Service, Url_Crud_Service, Url_Shorten_Service]
        test: [Authentication_Service, Url_Crud_Service, Url_Shorten_Service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build ${{ matrix.service }}
        run: |
          cd server/${{ matrix.service }}
          dotnet restore
          dotnet build --configuration Release
      - name: Run Unit Tests ${{ matrix.test }}
        run: |
          cd server/${{ matrix.test }}
          dotnet test --no-build --verbosity normal

  build_client:
    runs-on: ubuntu-latest
    needs: build_server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

  docker_push:
    runs-on: ubuntu-latest
    needs: [build_server, build_client]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      #Push to Docker Hub
      - name: Build & Push ApiGateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shortenurl-gateway:latest -f ./server/ApiGateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/shortenurl-gateway:latest

      - name: Build & Push Authentication_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shortenurl-auth_api:latest -f ./server/Authentication_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/shortenurl-auth_api:latest

      - name: Build & Push Url_Crud_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shortenurl-crud_service:latest -f ./server/Url_Crud_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/shortenurl-crud_service:latest

      - name: Build & Push Url_Shorten_Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shortenurl-url_shorten_service:latest -f ./server/Url_Shorten_Service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/shortenurl-url_shorten_service:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shortenurl-client:latest -f ./client/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/shortenurl-client:latest

      # Trigger Render Deploy
      # - name: Trigger All Services Deploy
      #   run: |
      #     curl -X POST ${{ secrets.RENDER_APIGATEWAY_HOOK }}
      #     curl -X POST ${{ secrets.RENDER_AUTH_HOOK }}
      #     curl -X POST ${{ secrets.RENDER_URLCRUD_HOOK }}
      #     curl -X POST ${{ secrets.RENDER_URLSHORTEN_HOOK }}
      #     curl -X POST ${{ secrets.RENDER_CLIENT_HOOK }}
